name: "IBM CR Build"
description: "IBM CR Build"
inputs:
  url: 
    description: "url server"
    required: true
  namespacetag: 
    description: "namespace name for the tag"
    required: true
  namespace: 
    description: "namespace name origin"
    required: true
  imagename: 
    description: "image name"
    required: true
  buildnr: 
    description: "build nr"
    required: true
  tag:
    description: "tag for docker"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.namespacetag }}
    - ${{ inputs.namespace }}
    - ${{ inputs.imagename }}
    - ${{ inputs.buildnr }}
    - ${{ inputs.tag }}
branding:
  color: 'green'
  icon: 'at-sign'
